theme = "tokyonight"

[editor]
true-color= true
cursorline = true
#line-number = "relative"
mouse = false
bufferline  = "multiple"
color-modes = true
auto-save = true

#Wrapping Techniques
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
soft-wrap.max-indent-retain = 10

#For Cursor
cursor-shape.insert = "bar"
cursor-shape.normal = "block"
cursor-shape.select = "underline"

#For Statusline
statusline.left = ["mode", "spinner","version-control","file-modification-indicator"]
statusline.center = ["file-name"]
statusline.right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
statusline.separator = " | "
statusline.mode.normal = "NORMAL"
statusline.mode.insert = "INSERT"
statusline.mode.select = "SELECT"

#for indent guides
indent-guides.render = true
indent-guides.character = "╎"
indent-guides.skip-levels= 1

#LSP support
lsp.enable = true
lsp.display-inlay-hints = true
lsp.display-messages = true
lsp.auto-signature-help = true
lsp.snippets = true
lsp.goto-reference-include-declaration = true


#File picker support
file-picker.hidden = false    


#Keys Section
[keys.insert]
C-s = [":w!", ":fmt"]   #saves the file in insert mode
[keys.normal]
"C-s" = ":w!"   #saves the file in normal mode  
"C-k"=":bc"   #kills the current buffer
"C-pagedown" = ":bn"  #Buffer Cycle
"C-q" = ":q!"  #quits helix
"esc" = ["collapse_selection", "keep_primary_selection"]  #escapes multiple selection
#minor mapping for nested backspace
[keys.normal.backspace]
r = [":config-reload"]
c = [":config-open"]




