theme = "tokyonight"

[editor]
true-color= true
cursorline = true
line-number = "relative"
mouse = false
bufferline  = "multiple"
color-modes = true
soft-wrap.enable = true
auto-save = true


[keys.insert]
C-s = [":w!", ":fmt"]   #saves the file in insert mode


[keys.normal]
"C-s" = ":w!"   #saves the file in normal mode  
"C-k"=":bc"   #kills the current buffer
"C-pagedown" = ":bn"  #Buffer Cycle
"C-q" = ":q!"  #quits helix
"esc" = ["collapse_selection", "keep_primary_selection"]  #escapes multiple selection
[keys.normal.backspace]
r = [":config-reload"]
c = [":config-open"]



[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = " | "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
snippets = true
goto-reference-include-declaration = true

[editor.file-picker]
hidden = false    #show hidden files
